slang_lookup={'AFAIK':" As Far As I Know ",
' AFK ':"Away From Keyboard",
'ASAP':"As Soon As Possible",
'ATK':"At The Keyboard",
'ATM':"At The Moment",
'A3':"Anytime, Anywhere, Anyplace",
'BAK':"Back At Keyboard",
'BBL':"Be Back Later",
'BBS':"Be Back Soon",
'BFN':"Bye For Now",
'B4N':"Bye For Now",
'BRB':"Be Right Back",
'BRT':"Be Right There",
'BTW':"By The Way",
'B4':"Before",
'B4N':"Bye For Now",
'CU':"See You",
'CUL8R':"See You Later",
'CYA':"See You",
'FAQ':"Frequently Asked Questions",
'FC':"Fingers Crossed",
'FWIW':"For What It's Worth",
'FYI':"For Your Information",
'GAL':"Get A Life",
'GG':"Good Game",
'GN':"Good Night",
'GMTA':"Great Minds Think Alike",
'GR8':"Great!",
'G9':"Genius",
'IC':"I See",
'ICQ':"I Seek you (also a chat program)",
'ILU':"I Love You",
'IMHO':"In My Honest/Humble Opinion",
'IMO':"In My Opinion",
'IOW':"In Other Words",
'IRL':"In Real Life",
'KISS':"Keep It Simple, Stupid",
'LDR':"Long Distance Relationship",
'LMAO':"Laugh My Ass Off",
'LOL':"Laughing Out Loud",
'LTNS':"Long Time No See",
'L8R':"Later",
'MTE':"My Thoughts Exactly",
'M8':"Mate",
'NRN':"No Reply Necessary",
'OIC':"Oh I See",
'PITA':"Pain In The Ass",
'PRT':"Party",
'PRW':"Parents Are Watching",
'ROFL':"Rolling On The Floor Laughing",
'ROFLOL':"Rolling On The Floor Laughing Out Loud",
'ROTFLMAO':"Rolling On The Floor Laughing My Ass Off",
'SK8':"Skate",
'STATS':"Your sex and age",
'ASL':"Age, Sex, Location",
'THX':"Thank You",
'TTFN':"Ta-Ta For Now!",
'TTYL':"Talk To You Later",
'U':"You",
'ur':"your",
'U2':"You Too",
'U4E':"Yours For Ever",
'WB':"Welcome Back",
'WTF':"What The Fuck",
'WTG':"Way To Go!",
'WUF':"Where Are You From?",
'W8':"Wait","m8":"might","Imma":"I am going to","\n":"","wouldnt":"would not","shouldnt":"should not","ive":"i have","bro":"brother","didnt":"did not","gotta":"got to","bruh":"brother","abt":"about","ppl":"people","havent":"have not","doesnt":"does not","intro":"introduction","tbh":"to be honest","idk":"I don't know","ain't": "am not", 'bs':'bull shit',"wht":"what","y":"why","shld":"should","wat":"what","dint":"did not","dunno":"do not know","thanx":"thanks","cmon":"csome on"}